from django.urls import path, re_path

from core import views

urlpatterns = [
    path("api/status", views.status),
    path("api/settings", views.settings_view),
    path("api/processors", views.processor_list),
    path("api/processors/check", views.processor_check),
    path("api/processors/detect", views.processor_detect),
    path("api/processors/<int:pid>", views.processor_detail),
    path("api/fs/roots", views.fs_roots),
    path("api/fs/list", views.fs_list),
    path("api/fs/file", views.fs_file),
    path("api/fs/detect-grammar", views.fs_detect_grammar),
    path("api/grammars", views.grammars),
    path("api/grammars/<int:gid>", views.grammar_detail),
    path("api/grammars/<int:gid>/activate", views.grammar_activate),
    path("api/grammars/<int:gid>/compile", views.grammar_compile),
    path("api/grammars/<int:gid>/files", views.grammar_files),
    path("api/parse", views.parse),
    path("api/generate", views.generate),
    path("api/processes", views.processes),
    path("api/processes/stop", views.processes_stop),
    path("api/profiles", views.profile_list),
    path("api/profiles/<int:pid>", views.profile_detail),
    path("api/profiles/<int:pid>/items", views.profile_items),
    path("api/profiles/<int:pid>/items/<int:iid>", views.profile_item),
    path("api/profiles/<int:pid>/run", views.profile_run),
    path("api/profiles/<int:pid>/cancel", views.profile_cancel),
    path("api/profiles/<int:pid>/compare/<int:other>", views.profile_compare),
    path("api/tfs/parse", views.tfs_parse),
    path("api/tfs/node", views.tfs_node),
    path("api/tfs/lookup", views.tfs_lookup),
    path("api/tfs/hierarchy", views.tfs_hierarchy),
    path("api/tfs/unify", views.tfs_unify),
    path("assets/<path:path>", views.assets),
    re_path(r"^(?!api/)(?P<path>.*)$", views.spa),
]
