# Generated by Django 5.2.17 on 2026-10-04 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_igde_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="aceconfig",
            name="profiles_dir",
            field=models.CharField(blank=True, default="", max_length=4096),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("path", models.CharField(max_length=4096)),
                ("kind", models.CharField(default="suite", max_length=8)),
                (
                    "grammar_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("owned", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("run_status", models.CharField(default="idle", max_length=16)),
                ("run_log", models.TextField(blank=True, default="")),
                (
                    "grammar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.grammar",
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="core.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "name", "id"],
            },
        ),
    ]
